updating support policy
SUSE/cap-release-notes pull request #87
Opened 2019-12-05 00:57 UTC by gaktive

Per @troytop's feedback in https://github.com/SUSE/cap-release-notes/issues/81

2019-12-05 01:03 UTC, btat approved these changes
LGTM

2019-12-16 22:44 UTC, troytop requested changes
A few changes required.

2019-12-16 22:44 UTC, troytop commented on adoc/support-statement.adoc
> +{product} is fully supported on {caaspa}, wherever it happens to be installed. If {caaspa} is supported on a particular CSP, the customer can get support for {product} in that context. (Note: This ha
Omit the parenthetical comment.

2019-12-16 22:44 UTC, troytop commented on adoc/support-statement.adoc
> +Technical Support and Troubleshooting (L1 - L2): Current and previous major versions (N-1). For example: {suse} will provide technical support and troubleshooting for versions 1.0, 1.1, 1.2, 1.3 (and
"N-1" should probably be "_n_ -1"

2019-12-16 22:44 UTC, troytop commented on adoc/support-statement.adoc
> +Patches and updates (L3): On the latest or last minor release of each major release. For example: {suse} will provide patches and updates for 1.3 (and 2.latest) until the release of 3.0.
maybe "2._latest_" (italic)

2019-12-16 22:46 UTC, gaktive commented on adoc/support-statement.adoc
> +{product} is fully supported on {caaspa}, wherever it happens to be installed. If {caaspa} is supported on a particular CSP, the customer can get support for {product} in that context. (Note: This ha
Gone.

2019-12-16 22:48 UTC, gaktive commented on adoc/support-statement.adoc
> +Technical Support and Troubleshooting (L1 - L2): Current and previous major versions (N-1). For example: {suse} will provide technical support and troubleshooting for versions 1.0, 1.1, 1.2, 1.3 (and
Italicized & lowercased.

2019-12-16 22:48 UTC, gaktive commented on adoc/support-statement.adoc
> +Patches and updates (L3): On the latest or last minor release of each major release. For example: {suse} will provide patches and updates for 1.3 (and 2.latest) until the release of 3.0.
Italicized.

2019-12-16 22:48 UTC, gaktive reviewed
Updated at @troytop's request.

2019-12-16 22:53 UTC, merged